repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0  # актуальная версия flake8
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2  # актуальная версия mypy
    hooks:
      - id: mypy
        additional_dependencies: []